name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    outputs:
      date: ${{ steps.build.outputs.date }}

    steps:
      - uses: actions/checkout@v3
      - name: Sanity check, if we are on Arch Linux environment
        run: |
          cat /etc/os-release
      - name: Install ArchISO
        run: |
          # Make sure container is up-to-date
          pacman -Syu --needed --noconfirm
          pacman -S git archiso --needed --noconfirm
      - name: Build ISO
        id: build
        run: |
          mkarchiso -v .
          find out

          export BUILD_DATE=$(date +'%Y.%m.%d')
          echo "date=${BUILD_DATE}" >> $GITHUB_OUTPUT
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'out/*.iso'
          tag: ${{ steps.build.outputs.date }}

## Refers
# https://github.com/theVakhovskeIsTaken/holoiso/blob/b27d0cf0a6bb673da0763f2ce89cd071169f0ed0/.github/workflows/build.yml
# https://github.com/crystal-linux/iso/blob/ff5c2373e9c04f859e9a068ea7db2843f0333731/.github/workflows/build.yml
